### ISSUE TITLE
poll interval

### ISSUE THREAD

**Issue by jtwhite79** [dwelter/pestpp#20]
@smwesten-usgs asked for this option to control the freq on YAMR slaves trying to connect to the master.  usage:
``++yamr_poll_interval(5)``
would be a 5 second polling interval.  I've added it to develop and I tested it a bit...seems to be working...

**Comment by smwesten-usgs** [comment]
Thanks Jeremy!

I still think there is nothing to be gained by allowing YAMR slaves unlimited, unthrottled attempts to connect to master. Hitting 'print' 50 times on your PC doesn't actually make your document print any faster!

I started a Condor run over the weekend that makes use of sweep master and worker to perform some Monte Carlo. I came in this morning (Monday) and find that Condor has dutifully logged std_err from a number of instances of sweep. For some the workers never stopped despite the master running to completion. The workers continued to try to reconnect to the master for the rest of the weekend. File size for those error logs? 156GB. Each. In every case, the first several thousand error messages are:

`failed to connect to master
connect error: (tcp/ip error id = 111) connection refused`

followed by several million messages reading:

`failed to connect to master
socket error: (tcp/ip error id = 24) Too many open files`

The latter message is possibly caused by too many open or borked sockets, which apparently count as open files in Linux land!

My vote would be to drastically restrict YAMR's attempts to connect to master by default. Once per second might be a reasonable default for polling, with a message written out once every 5 seconds.
