### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by hamiddashti** [dwelter/pestpp#34]
Hi, I'm very new to pest++. Since we had some problems compiling pest++ on our cluster, I decided to use the precompiled exe files from the release page (https://github.com/dwelter/pestpp/releases) located in exe/linux directory. I tried to run the twoline example of the pest manual using pestpp and I'm getting the following error: 
     using control file: "twofit.pst"
    .
    .
    .
     COMPUTING JACOBIAN:
      Iteration type: base parameter solution
        Segmentation fault

I'm not sure is that beacuse of using precomiled exe files or I'm doing something wrong? The template and instruction files are exactly same as the ones I used for pest. I attached my control file (in txt format) as well if that helps. Do you possibly have any idea what might be the issue? 
Thanks in advance for the help. 

[twofit.txt](https://github.com/dwelter/pestpp/files/2508057/twofit.txt)

**Comment by jtwhite79** [comment]
Sorry you are have issues - I wouldn't trust those precompiled linux binaries b/c there are too many dynamically-linked deps. We've compiled and used the suite on both a slurm/MPI cluster and on desktop ubuntu/fedora so I can be done!  If you have the intel C++ and fortran compiler available, that's the easiest since it includes MKL blas and lapack.  Otherwise, gcc (g++ and gfortran) 4,5,6,7 can be used as long as C++11 support is available - for the gcc build, you'll need to have blas and lapack available (can be found with `apt` on ubuntu).  The ``travis.yml`` on my fork ([https://github.com/jtwhite79/pestpp/tree/develop](https://github.com/jtwhite79/pestpp/tree/develop)) shows the ``make`` command line that travis is using:

``COMPILER=gcc6 CXX=g++-6 FC=gfortran-6 STATIC=no make install``

**Comment by hamiddashti** [comment]
@jtwhite79 Thanks!, we compiled it on our cluster. If no more comments I'll go ahead and close this issue.
