### ISSUE TITLE
Negative Sobol Indices

### ISSUE THREAD

**Issue by hamiddashti** [dwelter/pestpp#39]
Hi, I'm running PEST++ GSA with Sobol and I'm getting small negative numbers with respect to objective function (figure below) for some parameters. I tried different sampling size up to 1000 and the results are almost similar. I cannot do more than 1000 due to computation resources issue.

![image](https://user-images.githubusercontent.com/5567953/65907100-e8a5a680-e380-11e9-8358-b7cf231410b7.png)

Is PEST++ returns confidence interval on indices for each variables? I mean if the confidence interval includes zero and since these negative numbers are small, I assume I can safely turn this negative numbers into zero. 
Thanks

**Comment by jtwhite79** [comment]
@hamiddashti - the USGS version of the GSA utility ( PESTPP-SEN [https://github.com/usgs/pestpp](https://github.com/usgs/pestpp) as of version 4.2.16) has been reworked so that the sobol indices for a simple test problem are the same as those yielded by SALib.   Both GSA and PESTPP-SEN only report mean indices (not confidence intervals).  PESTPP-SEN can be extended to yield confidence intervals on the indices, just havent gotten around to it yet.

**Comment by hamiddashti** [comment]
Git it! Thank you. I'll go ahead and close this issue.
